todo/urls.py
from django.conf.urls import url
#importando de la clase index2 de views
urls de la aplicacion todo
from . import views

urlpatterns = [
    url(r'^$', views.index2, name='index2'),
]

todolist/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#url general de proyecto
urlpatterns = [
	url(r'^todo/', include('todo.urls')),
    url(r'^admin/', admin.site.urls),
]

todo/models.py
# -*- encoding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Todo(models.Model):
	nombre = models.CharField('Nombre',
								max_length=200,
								help_text='Ingrese nombre del proyecto')
	def __str__(self):
		return self.nombre

	class Meta:
		ordering = ('nombre',)


class TodoArticulo(models.Model):
	fktodo = models.ForeignKey(Todo)
	tarea = models.TextField('Tareas',help_text = 'Descripción de la tarea')
	fecha = models.DateField()

	def __str__(self):
		return u'%s | %s ' % (self.fktodo, self.tarea)

	class Meta:
		verbose_name=u'Todo Tarea'
		verbose_name_plural = 'Todo Tareas'

todo/views.py
from django.shortcuts import render
from django.shortcuts import render_to_response, get_object_or_404
from django.template import RequestContext
from todo.models import Todo, TodoArticulo
from django.http import HttpResponse
# Create your views here.
# esta es mi primera rama de nombre rama1
def index(request):
	todo = Todo.objects.all() # select * from Todo
	return render_to_response('index.html',
								RequestContext(request.locals()))


def ver_detalle(request, id):
		#ver2 = Todo.objects.filter(id = id) esta es otra forma
	ver = get_object_or_404(Todo,id=id)
	return render_to_response('todo/ver.html',
								RequestContext(request.locals()))
def index2(request):
    return HttpResponse("Hello, world. You're at the polls index.")

templates/index.html
{% block contenido %}
{% for dato in todo %}
			<div class="span4">
				<h2>{{dato}}</h2>
				<p><a class="btn" href="/ver_articulo/{{dato.id}}">Ver tareas del proyecto &raquo;</a></p>
			</div><!--/span-->
{% empty %}
	<p> No hay datos</p>
{% endfor %}

{% endblock contenido %}

templates/todo/ver.html
{% extends "base.html" %}
{% block contenido %}
	<h2>{{ver.nombre}}</h2>
	{% for obj in ver.todoarticulo_set.all %}
		{{obj.tarea}} </br>
		{{obj.fecha}}
		<hr>
	{% empty %}
	<p>No hay tareas para este proyeto</p>
	{% endfor %}
{% endblock contenido %}